#!/bin/bash -f

maxiter=$1
width=$2
height=$3
lower_r=$4
upper_r=$5
lower_i=$6
upper_i=$7
nb_threads=$8
loadbalance=$9

make MAXITER=$maxiter WIDTH=$width HEIGHT=$height LOWER_R=$lower_r UPPER_R=$upper_r LOWER_I=$lower_i UPPER_I=$upper_i NB_THREADS=$nb_threads LOADBALANCE=$loadbalance GLUT=0 MEASURE=1
